### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by GithubforBen** [DemonWav/MinecraftDevIntelliJ#2143] opened 2023-10-13 13:59 UTC
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

2023.2.3

### Operating System

Windows

### Target platform

Paper

### Description of the bug

When I click new project nothing happens. There is no error message or anything like that. just nothing happens.

**Comment by RedNesto** [comment] 2023-10-13 14:02
Duplicate of #2140

**Closed as completed by RedNesto** 2023-10-13 14:02 UTC
Labels: type: bug, status: unverified
