### ISSUE TITLE
Add DSL selection gradle

### ISSUE THREAD

**Issue by dd2x2** [DemonWav/MinecraftDevIntelliJ#2117] opened 2023-08-30 15:44 UTC
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### Description of the feature request

please, when choosing gradle, add the ability to choose between Groovy DSL and Kotlin DSL

**Comment by lucyydotp** [comment] 2023-08-31 11:30
Duplicate of #1898?

**Comment by Tennessene** [comment] 2023-12-24 20:59
I agree with this, but this is a duplicate of #687

**Closed as completed** 2023-12-24 22:03 UTC
Labels: type: enhancement, status: unverified
