### ISSUE TITLE
Support 1.7.10 

### ISSUE THREAD

**Issue by Kotikstar** [DemonWav/MinecraftDevIntelliJ#931] opened 2021-05-29 19:56 UTC
please add support for 1.7.10. It is relevant for the community.

**Comment by RedNesto** [comment] 2021-05-29 20:01
This won't happen, see https://github.com/minecraft-dev/MinecraftDev/issues/591#issuecomment-475997683

**Comment by Ayfri** [comment] 2021-05-29 20:01
Duplicate of #802, #591, #312, #165 & #76.

**Closed as completed** 2021-05-29 20:01 UTC
Labels: status: wontfix
