### ISSUE TITLE
Spigot support for 1.8.8

### ISSUE THREAD

**Issue by Marcelektro** [DemonWav/MinecraftDevIntelliJ#739] opened 2020-07-05 10:26 UTC
Hello. Im using your plugin MC Dev. It works perfectly fine for Bungeecord, however, I would need support for 1.8 spigot in order to use it in Spigot developement.
Is there a chance of adding support to it?
Regards

**Comment by RedNesto** [comment] 2020-07-05 10:28
https://github.com/minecraft-dev/MinecraftDev/issues/727#issuecomment-650534713
Duplicate of #727

**Closed as completed by RedNesto** 2020-07-05 10:28 UTC
Labels: status: invalid, type: question, status: wontfix
