### ISSUE TITLE
How to decompile mc?

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#311] opened 2017-10-07 05:50 UTC
When I create a new liteloader mod, it only lets me build, how can I run the mod

**Comment by DenWav** [comment] 2017-10-14 07:25
To setup the LiteLoader run config, run the Gradle task provided by ForgeGradle `genIntellijRuns`. MCDev should automatically run this task during project setup, but I haven't gotten to adding that yet.

**Comment by DenWav** [comment] 2017-10-14 07:26
Duplicate of #111.

**Closed as completed by DenWav** 2017-10-14 07:26 UTC
Labels: type: duplicate, platform: liteloader
