### ISSUE TITLE
Support Architectury API

### ISSUE THREAD

**Issue by KP2048** [DemonWav/MinecraftDevIntelliJ#1793] opened 2022-01-12 23:28 UTC
Architectury API makes it possible to have both forge and fabric projects share common code and any forge/fabric specific things go in their respective sub projects

https://github.com/architectury/architectury-templates

**Comment by zml2008** [comment] 2022-01-13 00:47
What support would you like to see from MinecraftDev? Doesn't architectury have their own IntelliJ plugin already?

**Comment by zml2008** [comment] 2022-01-13 00:48
(also duplicate of #823)

**Closed as completed** 2022-01-13 03:09 UTC
Labels: type: enhancement, status: unverified

**Comment by KP2048** [comment] 2022-01-13 13:38
I kind wanted a project template but ok
Their plug-in just makes it so their @ExpectPlatform annotation can generate implementation classes.

**Comment by Earthcomputer** [comment] 2022-01-13 14:19
It was closed because it was a duplicate, not because it was rejected.

**Comment by KP2048** [comment] 2022-01-13 20:11
ok
