### ISSUE TITLE
[FEATURE-REQUEST] Support with Kotlin

### ISSUE THREAD

**Issue by TheFruxz** [DemonWav/MinecraftDevIntelliJ#749] opened 2020-07-19 14:50 UTC
# My FEATURE_REQUEST
__Dear readers__, I have been a bukkit plugin developer for several years and have learned several libraries, APIs and programming languages over the years. For some time now, I've even been developing my Minecraft plugins using only Kotlin, so I asked if you could possibly add a way to switch between Java and Kotlin in addition to the option between Gradle and Maven. This would help some developers to be freer in developing. 

> _Thank you_ for taking the time to read through this request!

**Comment by Username404-59** [comment] 2020-07-27 10:30
I approve this! 
Being able to create kotlin mods for fabric easily would be nice too 😃.

**Comment by Earthcomputer** [comment] 2020-07-27 15:00
Duplicate of #722

**Comment by TheFruxz** [comment] 2020-07-28 17:47
> Duplicate of #722

Then I think it is really necessary to add such a feature

**Comment by DenWav** [comment] 2020-08-18 16:19
Yes I completely agree adding Kotlin support would be nice and I would like to do it as well. Please understand the lack of Kotlin support is a technical limitation (as explained in the linked ticket) and not simply a decision not to do so. We don't need to be convinced to add this, it has nothing to do with that. It's purely a technical blocker which has - at least in the past - prevented us from implementing this. That blocker may not still exist or be as large as it used to, but further investigation is required.

**Closed as completed by DenWav** 2020-08-18 16:19 UTC
Labels: type: enhancement, status: unverified

**Comment by TheFruxz** [comment] 2020-08-25 21:59
I don't see a problem in using Kotlin on a bukkit server, because libraries from e.g. [https://dev.bukkit.org/projects/kotlin](https://dev.bukkit.org/projects/kotlin) are adding the "compatibility".

For comparison, Forge usually has to be installed on the server **AND** even _manually_ by the user, Kotlin has to be added **ONLY** as a _default_ plugin by the administrator

**Comment by Earthcomputer** [comment] 2020-08-25 22:00
As demon said, it's a technical issue, and also this issue is a duplicate.
