### ISSUE TITLE
NullPointerException in Railcraft development

### ISSUE THREAD

**Issue by liach** [DemonWav/MinecraftDevIntelliJ#341] opened 2018-01-14 21:40 UTC
https://gist.github.com/anonymous/b6851cb650fa76173a092cf4ae9ff349

Idea later says that there were too many errors so that its monitoring stopped.

**Comment by liach** [comment] 2018-01-14 21:41
And what's worse, I cannot submit this issue within the ide using your bot.

**Comment by liach** [comment] 2018-01-14 21:42
More info: branch: liach-1.10.2
happens when I ctrl+alt+l reformat code or at other times.

**Comment by DenWav** [comment] 2018-01-15 07:43
Duplicate of #338.

Fixed in 822607e.

The fix will be deployed in the new release tomorrow. Otherwise, use the nightly build for the time being.

**Closed as completed by DenWav** 2018-01-15 07:43 UTC
Labels: type: bug, type: duplicate, platform: forge

**Comment by liach** [comment] 2018-01-15 08:42
Hmm. I thought I updated yesterday. This does not affect most of the features, such as sideonly checks, so it's fine.
