### ISSUE TITLE
Fabric showing no versions at the select list

### ISSUE THREAD

**Issue by housey2k** [DemonWav/MinecraftDevIntelliJ#1845] opened 2022-06-03 17:00 UTC
* Minecraft Development for IntelliJ plugin version 2022.1-1.5.19
* IntelliJ version 2022.1.2
* Operating System Win11
* Target platform: Fabric 1.18.2

The problem im having, is that when i select fabric mod at the plugin, i do everything normal, but at the Fabric Settings page, yarn version, fabric version, minecraft version, the select list shows nothing, and if i create the project it will not be built correctly, will have missing files
![image](https://user-images.githubusercontent.com/67515570/171911477-5bc3d5ef-030e-471b-9ca3-801ffddee942.png)

**Comment by colbiedison** [comment] 2022-06-03 17:16
Having the same problem.
Plugin version: 2021.3-1.5.19
IntelliJ IDEA 2021.3.3 (Ultimate Edition)
OS: Arch Linux
Target platform: Fabric 1.18.2
![image](https://user-images.githubusercontent.com/46203390/171913725-bd2f70cf-0a6f-4bd1-829b-e8cef1935343.png)

**Comment by ashenaeris** [comment] 2022-06-03 19:08
Same issue here.
Plugin version: 2022.1-1.5.19
IntelliJ version: 2022.1.1
OS: Garuda Linux
Target: Fabric (can't pick a version)
![image](https://user-images.githubusercontent.com/105615443/171932181-abe17bf8-0b84-4580-b506-04830b719d1d.png)

**Comment by RedNesto** [comment] 2022-06-03 20:08
Duplicate of #1829

**Closed as completed by RedNesto** 2022-06-03 20:08 UTC
Labels: type: bug, type: duplicate
