### ISSUE TITLE
Access to CraftEntity etc..

### ISSUE THREAD

**Issue by Gezellligheid** [DemonWav/MinecraftDevIntelliJ#815] opened 2021-01-09 15:55 UTC
Soo The default spigot/paper does not have the CraftEntities, CraftArmorstand, etc... in their library but they have an seperate build that has to be build in order to use them in your code.

Maybe handyto implement that aswel?

**Comment by DenWav** [comment] 2021-01-10 09:49
Duplicate of #762

**Closed as completed by DenWav** 2021-01-10 09:49 UTC
Labels: type: duplicate, type: enhancement, status: unverified
