### ISSUE TITLE
PaperSpigot 1.15 not generate sources

### ISSUE THREAD

**Issue by IM-IgniteDEV** [DemonWav/MinecraftDevIntelliJ#738] opened 2020-07-04 09:30 UTC
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version 

![image](https://user-images.githubusercontent.com/31209154/86509582-5cca1a80-bde9-11ea-9d55-f71a3094299d.png)

* IntelliJ version

![image](https://user-images.githubusercontent.com/31209154/86509584-65225580-bde9-11ea-98f3-1abfc7fb2396.png)

* Operating System: Windows 10

The default paperspigot 1.15 downloaded by minecraft development have not generated sources  as you can see on image, manual looking for sources not working too.

![image](https://user-images.githubusercontent.com/31209154/86509608-86834180-bde9-11ea-88d1-7e79459dbe68.png)

![image](https://user-images.githubusercontent.com/31209154/86509630-a74b9700-bde9-11ea-8a7b-6baeabf0a80a.png)

![image](https://user-images.githubusercontent.com/31209154/86509641-b16d9580-bde9-11ea-9c49-62f38978aaf7.png)

**Comment by RedNesto** [comment] 2020-07-04 09:55
I cannot reproduce, make sure `Automatically download: sources` is checked in `File | Settings | Build, Execution, Deployment | Build Tools | Maven | Importing`

**Comment by IM-IgniteDEV** [comment] 2020-07-06 17:22
![image](https://user-images.githubusercontent.com/31209154/86621166-0235e780-bfbe-11ea-96b9-d64aede1de67.png)


It is.

**Comment by RedNesto** [comment] 2020-07-07 08:56
Well, I have no idea what's wrong then (I'm not a Maven user so I can't help much more). I doubt this is a problem with our plugin anyway.

**Closed as completed by RedNesto** 2020-07-07 08:56 UTC
Labels: type: bug, status: cannot reproduce

**Comment by yannicklamprecht** [comment] 2020-07-07 09:38
Scope is provided?
