### ISSUE TITLE
Setup does not finish correctly

### ISSUE THREAD

**Issue by MrSam7K** [DemonWav/MinecraftDevIntelliJ#2054] opened 2023-06-10 09:39 UTC
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

2023.1.2

### Operating System

Windows

### Target platform

Fabric

### Description of the bug

Main classes (`./client/<project>Client` and `<project>`) 
![image](https://github.com/minecraft-dev/MinecraftDev/assets/64192417/bc96b466-94bf-49ca-811c-ebace5b85c31)
never setups correctly and inside looks like this:
![image](https://github.com/minecraft-dev/MinecraftDev/assets/64192417/628c2e38-4877-4e50-8b2d-5f582841872c)
![image](https://github.com/minecraft-dev/MinecraftDev/assets/64192417/cf463083-cacb-44c9-ab50-f1aad474f92a)
without any imports, package and sample code with `ModInitializer`, `ClientModInitializer` and etc.
No errors anywhere

**Comment by Nekiplay** [comment] 2023-06-11 18:19
I have the same problem

**Comment by CodeCraftPlugin** [comment] 2023-06-14 06:08
I too have the same problem even shifted to the nightly build still persist

**Comment by MrSam7K** [comment] 2023-06-17 20:17
In my opinion this should be treated quite seriously since it's mostly main feature of this plugin.

**Comment by CodeCraftPlugin** [comment] 2023-06-19 07:52
yeah exactly

**Comment by AnOpenSauceDev** [comment] 2023-06-27 00:34
I've also been having the same issue with this, and i got it to occasionally work by killing the process, and running it again.

**Comment by MarcPG1905** [comment] 2023-06-29 21:08
I have the same issue, I tried recreating the project multiple times and closing every file in the hopes of it maybe just bugging because it can't overwrite opened files, but that didn't help either.

**Comment by AnOpenSauceDev** [comment] 2023-07-05 20:44
I think i found a working solution, but it's not the smartest workaround.

1. Start Intellij IDEA **as root** (haven't tested on windows)
2. Install the Minecraft Dev plugin again (you will have to, as root treats this like a new install)
3. create your project as usual (my test setup below)
![Screenshot from 2023-07-06 06-26-37](https://github.com/minecraft-dev/MinecraftDev/assets/119765865/5e63fcce-9447-4851-8810-15b547e4c54a)
4. the project should have all the correct imports, boilerplate, and package names working.
![Screenshot from 2023-07-06 06-34-13](https://github.com/minecraft-dev/MinecraftDev/assets/119765865/18dab81e-6d71-46db-a688-e0991dff5c51)
This should work on any Linux distro, but I haven't tried it yet on my Artix machine.

The only major issue i have with this "fix" is that you have to run _everything_ with superuser privileges, **which is ALWAYS a bad idea, especially when dealing with untrusted code**.
The actual issue is probably something to do with file permissions, which would explain it only working as root.

_and yes, it compiles_
![Screenshot from 2023-07-06 06-50-57](https://github.com/minecraft-dev/MinecraftDev/assets/119765865/1b34bdaa-5544-4e2f-b5d5-ffa2130f70fc)

**Comment by AnOpenSauceDev** [comment] 2023-07-05 21:18
same issue as #1998

**Comment by CodeCraftPlugin** [comment] 2023-07-09 12:28
hey this says that they fixed the issue
[commit](https://github.com/minecraft-dev/MinecraftDev/commit/9f5ca6f6a261ede99d06451d946084d3bd0e4c12)

**Comment by RedNesto** [comment] 2023-07-09 13:22
I tried everything I could to fix this issue. i can't replicate it anymore on my end since the commit linked above.

Make sure you leave ALL the background tasks end by themselves, especially the index-related tasks that are paused during the initial Gradle import.

**Comment by Earthcomputer** [comment] 2023-07-09 17:11
Some of the steps are meant to be run in smart mode *after* the gradle import has finished. Does it do this?

**Comment by RedNesto** [comment] 2023-07-09 17:21
> Some of the steps are meant to be run in smart mode after the gradle import has finished. Does it do this?

They do, but if you happen to resume any of the paused indexing tasks before the gradle import is done it will indeed generate the bare classes without populating them with a package import and the appropriate overrides.

That's why for now I'm suspecting that some users interfere with the setup process at some point.

**Comment by AnOpenSauceDev** [comment] 2023-07-09 23:19
But that's the thing- usually leave my computer and go do something else while everything gets set up, and when i return, this issue happens. I have not stopped any process from running either, and have had this problem on two computers, both running different distro bases of Linux (Debian, Arch) and even on a windows partition.

**Comment by SzczurekYT** [comment] 2023-07-10 09:40
I uninstalled the plugin, installed it, to make sure it's the latest version (2023-1.6.7) and it looks like if you don't do anything it actually finally works.
I'm on Nobara 38 (derived from Fedora), intellij is installed as snap.

**Comment by AnOpenSauceDev** [comment] 2023-07-10 21:11
> I uninstalled the plugin, installed it, to make sure it's the latest version (2023-1.6.7) and it looks like if you don't do anything it actually finally works. I'm on Nobara 38 (derived from Fedora), intellij is installed as snap.

Odd, did a full reinstall, and nothing changed. Could it be that the use of a sandbox fixes the permission issue?

**Comment by CodeCraftPlugin** [comment] 2023-07-11 16:27
Hi So i tried running intellij as admin on windows and it still does not fix it

**Comment by SzczurekYT** [comment] 2023-07-11 19:49
> Hi So i tried running intellij as admin on windows and it still does not fix it  

Here most of the comments talk about Linux, which has very different permission system then linux, so if this is a permission problem windows admin isn't probably going to help.
But if you have the problem on windows then we have an another confirmation that mod not generating correctly is still an issue, and it's probably not permission related if it occurs on two completly different os'es.
If I will remember I will try how's the situation in my windows tomorrow.
@RedNesto What informations should we send, so our reports are usefull for debugging?

**Comment by RedNesto** [comment] 2023-07-11 20:24
> What informations should we send, so our reports are usefull for debugging?

Honestly I don't know, I tried everything I could on my end to fix it and I can't reproduce it anymore since the last fix I committed about it. Tried on Windows and Ubuntu, using Jetbrains Toolbox in both.

Someone affected by the issue could try to debug it on their end, for example look if the IDE doesn't switch to smart mode early for some reason (before the indexing task is finished) and the code we use to generate the classes runs at that time.

There could still be multiple causes to this issue, and not necessarily obvious ones, for example timing shenanigans happening based on CPU and/or IO speed.

**Comment by AnOpenSauceDev** [comment] 2023-07-11 21:32
> > Hi So i tried running intellij as admin on windows and it still does not fix it
> 
> Here most of the comments talk about Linux, which has very different permission system then linux

Also couldn't get this working on windows, still had the error, but Admin on windows doesn't have FULL disk access, if that's anything.

>There could still be multiple causes to this issue, and not necessarily obvious ones, for example timing shenanigans happening based on CPU and/or IO speed.

Even if its one of those obscure problems, why does it work as root? It's still running _the native version_ of Intellij, from the same directory, just with higher level permissions. This part just really confuses me.

**Comment by MrSam7K** [comment] 2023-07-13 11:44
> Honestly I don't know, I tried everything I could on my end to fix it and I can't reproduce it anymore since the last fix I committed about it. Tried on Windows and Ubuntu, using Jetbrains Toolbox in both.

It still occurs even in nightly build (2023.1-1.1.6.7-406)

**Comment by AnOpenSauceDev** [comment] 2023-07-15 10:42
Just tested the project creator wizard for Architectury as non-root, and it worked fine? **This issue only seems to affect fabric** _(have not tested forge.)_, and everything runs fine.

**Comment by SzczurekYT** [comment] 2023-07-15 10:56
Yeah, Architectury works fine. 
Yesterday I updated to latest nightly release and it failed to generate a mod properly again. I have no idea what's wrong with this. When you don't need it, it works, when you need it, it doesn't.

**Comment by AnOpenSauceDev** [comment] 2023-07-15 11:00
> Yeah, Architectury works fine. Yesterday I updated to latest nightly release and it failed to generate a mod properly again. I have no idea what's wrong with this. When you don't need it, it works, when you need it, it doesn't.

I find it weird that the codebases for creating the structures are seemingly different, and that sudo perms fix it for reasons that make no sense to me.

**Comment by AnOpenSauceDev** [comment] 2023-08-10 23:24
At some point this issue... magically fixed itself? I have no idea if this has anything to do with me switching to JetBrains Toolbox, an Intellij update, or if the devs fixed the bug.

**Closed as completed** 2023-08-13 18:20 UTC
Labels: type: bug, type: duplicate

**Comment by AnOpenSauceDev** [comment] 2023-10-22 01:43
Creating projects was fine about ~7 days ago when I threw together a small mod, but the bug is seemingly back today...
![Screenshot from 2023-10-22 11-39-22](https://github.com/minecraft-dev/MinecraftDev/assets/119765865/9a1d1908-1b6f-448b-a8f0-e4d0ac1dca73)
basically, the exact same issue as before. (Only tested on Linux)
