### ISSUE TITLE
At inspections flag `<clinit>` as an unresolved target

### ISSUE THREAD

**Issue by ChloeDawn** [DemonWav/MinecraftDevIntelliJ#489] opened 2019-02-11 22:56 UTC
```
Minecraft Development for IntelliJ 2018.3-1.2.11
IntelliJ IDEA 2018.3.3 (Community Edition)
Build #IC-183.5153.38, built on January 9, 2019
Windows 10 10.0
```
Inspections run on the `@At` annotation, mark `<clinit>` as an unresolved target, which is an untrue statement.

![inspection tooltip](https://i.imgur.com/YzFFNgh.png)

An example mixin that I wrote for someone can be seen below, with a valid use of `<clinit>` injection. It compiles and injects successfully, yet the plugin marks this as an error.

```java
@Mixin(GlStateManager.class)
abstract class GlStateManagerMixin {
  private GlStateManagerMixin() {}

  @SuppressWarnings("UnresolvedMixinReference")
  @ModifyArg(
    method = "<clinit>",
    at = @At(value = "INVOKE", target = "Ljava/util/stream/IntStream;range(II)Ljava/util/stream/IntStream;"),
    slice = @Slice(
      from = @At(value = "FIELD", target = "Lcom/mojang/blaze3d/platform/GlStateManager;NORMALIZE:Lcom/mojang/blaze3d/platform/GlStateManager$CapabilityTracker;"),
      to = @At(value = "FIELD", target = "Lcom/mojang/blaze3d/platform/GlStateManager;shadeModel:I")
    ),
    index = 1,
    remap = false
  )
  private static int increaseTexturesBuffer(final int max) {
    return 32;
  }
}
```

**Comment by ChloeDawn** [comment] 2019-02-11 23:06
Here is a simple test case and result, as a clearer example of `<clinit>` being a valid target ^^

**Target:**
```java
package foo.bar;

public final class FooBar {
  public static final int BAZ = baz(8);
  
  private static int baz(final int i) {
    return 16 + i;
  }
}
```
**Mixin:**
```java
package foo.bar.mixin;

@Mixin(FooBar.class)
abstract class FooBarMixin {
  private FooBarMixin() {}

  @ModifyArg(
    method = "<clinit>",
    at = @At(
      value = "INVOKE",
      target = "Lfoo/bar/FooBar;baz(I)I"
    )
  )
  private static int abc(final int i) {
    return i * 2;
  }
}
```
**Result:**
```java
package foo.bar;

import org.spongepowered.asm.mixin.transformer.meta.MixinMerged;

public final class FooBar {
  public static final int BAZ;

  public FooBar() {
  }

  private static int baz(int i) {
    return 16 + i;
  }

  static {
    byte var0 = 8;
    BAZ = baz(modify$abc$zbm000(var0));
  }

  @MixinMerged(
    mixin = "foo.bar.mixin.FooBarMixin",
    priority = 1000,
    sessionId = "40e0d074-ca87-4b9c-afd2-7962e684b80b"
  )
  private static int modify$abc$zbm000(int i) {
    return i * 2;
  }
}
```

**Comment by DenWav** [comment] 2019-02-13 05:50
`<clinit>` should be supported, weird.

**Comment by DenWav** [comment] 2019-03-16 04:17
Duplicate of #355

**Closed as completed by DenWav** 2019-03-16 04:17 UTC
Labels: type: bug, type: duplicate, platform: mixins
