### ISSUE TITLE
Minestom basic server template

### ISSUE THREAD

**Issue by AndusDEV** [DemonWav/MinecraftDevIntelliJ#2121] opened 2023-09-03 12:26 UTC
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### Description of the feature request

A project template for creating a [Minestom](https://minestom.net/) server

**Comment by RedNesto** [comment] 2023-09-24 08:56
Duplicate of #835

**Closed as completed by RedNesto** 2023-09-24 08:56 UTC
Labels: type: enhancement, status: unverified
