### ISSUE TITLE
NPE trying to paste a new plugin class.

### ISSUE THREAD

**Issue by gabizou** [DemonWav/MinecraftDevIntelliJ#400] opened 2018-06-13 00:05 UTC
MinecraftDev: 2018.1-1.2.1
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

With the following class from this issue: 
```java
package net.shmeeb.testing;

import org.spongepowered.api.Sponge;
import org.spongepowered.api.command.CommandResult;
import org.spongepowered.api.command.CommandSource;
import org.spongepowered.api.command.args.CommandContext;
import org.spongepowered.api.command.spec.CommandExecutor;
import org.spongepowered.api.command.spec.CommandSpec;
import org.spongepowered.api.data.DataContainer;
import org.spongepowered.api.data.persistence.DataFormats;
import org.spongepowered.api.data.type.HandTypes;
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.game.state.GameInitializationEvent;
import org.spongepowered.api.item.inventory.ItemStack;
import org.spongepowered.api.item.inventory.ItemStackSnapshot;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;
import org.spongepowered.api.text.serializer.TextSerializers;

import java.io.IOException;

@Plugin(id = "testing", name = "Testing", version = "1.0")
public class Main {
    private static String ITEM_STRING = null;

    @Listener
    public void init(GameInitializationEvent e) throws IOException {
        registerCommands();
    }

    private void registerCommands() {
        CommandSpec save = CommandSpec.builder()
                .executor(new CommandExecutor() {
                    @Override
                    public CommandResult execute(CommandSource commandSource, CommandContext commandContext) {
                        Player player = (Player) commandSource;

                        if (!player.getItemInHand(HandTypes.MAIN_HAND).isPresent()) {
                            sendMessage(player, "&cYou must be holding an item in your hand to create a ChestShop");
                            return CommandResult.empty();
                        }

                        ItemStack item = player.getItemInHand(HandTypes.MAIN_HAND).get();
                        ItemStackSnapshot snapshot = item.createSnapshot();
                        String json = null;

                        try {
                            json = DataFormats.JSON.write(snapshot.toContainer());
                        } catch (IOException e) {
                            e.printStackTrace();
                        }

                        ITEM_STRING = json;
                        System.out.println("saved: " + ITEM_STRING);

                        return CommandResult.success();
                    }
                }).build();

        CommandSpec check = CommandSpec.builder()
                .executor(new CommandExecutor() {
                    @Override
                    public CommandResult execute(CommandSource commandSource, CommandContext commandContext) {
                        Player player = (Player) commandSource;
                        DataContainer container = null;

                        try {
                            container = DataFormats.JSON.read(ITEM_STRING);
                        } catch (IOException e) {
                            e.printStackTrace();
                            return CommandResult.empty();
                        }

                        ItemStackSnapshot snapshot = Sponge.getDataManager().deserialize(ItemStackSnapshot.class, container).get();

                        if (player.getInventory().contains(snapshot.createStack())) {
                            sendMessage(player, "Your inv contains the stored item");
                        } else {
                            sendMessage(player, "Your inv does not contain the stored item");
                        }

                        return CommandResult.success();
                    }
                }).build();

        Sponge.getCommandManager().register(this, save, "cssave");
        Sponge.getCommandManager().register(this, check, "cscheck");
    }

    public static String color(String string) {
        return TextSerializers.FORMATTING_CODE.serialize(Text.of(string));
    }

    public static void sendMessage(CommandSource sender, String message) {
        sender.sendMessage(TextSerializers.FORMATTING_CODE.deserialize(color(message)));
    }
}
```
I'm getting this NPE:
```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendInternalName(bytecode-utils.kt:74)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:84)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:137)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.getDescriptor(bytecode-utils.kt:132)
	at com.demonwav.mcdev.util.MemberReferenceKt.getQualifiedMemberReference(MemberReference.kt:128)
	at com.demonwav.mcdev.util.MemberReferenceKt.isSameReference(MemberReference.kt:136)
	at com.demonwav.mcdev.util.Call_utilsKt.getCallsReturningResult(call-utils.kt:77)
	at com.demonwav.mcdev.i18n.translations.TranslationFunction.getCalls(TranslationFunction.kt:54)
	at com.demonwav.mcdev.i18n.translations.TranslationFunction.matches(TranslationFunction.kt:47)
	at com.demonwav.mcdev.i18n.translations.identifiers.TranslationIdentifier$Companion.identify(TranslationIdentifier.kt:47)
	at com.demonwav.mcdev.i18n.translations.identifiers.LiteralTranslationIdentifier.identify(LiteralTranslationIdentifier.kt:21)
	at com.demonwav.mcdev.i18n.translations.identifiers.LiteralTranslationIdentifier.identify(LiteralTranslationIdentifier.kt:17)
	at com.demonwav.mcdev.i18n.translations.identifiers.TranslationIdentifier.identifyUnsafe(TranslationIdentifier.kt:29)
	at com.demonwav.mcdev.i18n.translations.Translation$Companion.fold(Translation.kt:109)
	at com.demonwav.mcdev.i18n.I18nFoldingBuilder.buildFoldRegions(I18nFoldingBuilder.kt:20)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:63)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:236)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:222)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:99)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$updateFoldRegions$0(FoldingUpdate.java:88)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:84)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:310)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:296)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

What's happening in the end is that the file is not recognized as a java file anymore and no inspections are functioning, let alone auto-completion.

I think it's easy to replicate by simply pasting even the class header with the annotation for a plugin. Currently attempting to add this to the SpongeCommon test plugins suite.

**Comment by DenWav** [comment] 2018-06-13 05:12
Again, your plugin (and IDE for that matter) was out of date (`2018.1-1.2.1`, current released version is `2018.1-1.2.7`). `1.2.1` was released 3 months ago...

This was fixed in a87f054c67.

Duplicate of #388.

**Closed as completed by DenWav** 2018-06-13 05:12 UTC
Labels: type: duplicate
