### ISSUE TITLE
Support for Gradle kts

### ISSUE THREAD

**Issue by raphael950** [DemonWav/MinecraftDevIntelliJ#1898] opened 2022-10-02 17:31 UTC
Hello, I saw that we can create plugins using Gradle and Maven, could you also add support for Grdle kts pls?

**Comment by AlmanaX-21** [comment] 2023-09-01 09:52
Are there plans on working towards this?

**Comment by OakLoaf** [comment] 2023-10-18 16:24
Yeahh I'd also like gradle kts support

**Comment by GhostGonz21st** [comment] 2023-12-10 21:29
woul like this as well. It would make things alot faster than starting from scratch.

**Comment by Tennessene** [comment] 2023-12-24 21:00
I agree with this too, but this is a duplicate of #687

**Closed as completed** 2023-12-24 22:03 UTC
Labels: type: enhancement, status: unverified
