### ISSUE TITLE
@SideOnly inspection triggered in proxy classes

### ISSUE THREAD

**Issue by Redrield** [DemonWav/MinecraftDevIntelliJ#48] opened 2016-08-19 22:59 UTC
While experimenting with Forge modding, with this plugin installed, I found that when referencing classes annotated @SideOnly(Side.CLIENT) in my ClientProxy, the inspection warnings were triggered (As proxy classes aren't annotated.)

As I'm aware that DemonWav isn't the most familiar with Forge, I'll explain. A typical forge mod will have 3 proxy classes, CommonProxy, ClientProxy, and ServerProxy (The second 2 extending the first). CommonProxy contains initializations for code common to both platforms, while ClientProxy contains client specific initializations (Code that won't be run on the server), and ServerProxy is the same (For servers).

**Comment by DemonWav** [comment] 2016-08-20 03:24
I know of the Proxy, I just haven't figure out how to handle that.

**Comment by Redrield** [comment] 2016-08-20 16:12
I'm not sure if this would work, but when making an instance of the CommonProxy object, it should be annotated as @SidedProxy, and the values passed to that annotation are the classpaths of the other 2 proxies. If it's possible to read those values and store them in a global variable, then check if the classpath of the class the SideOnly inspection is being triggered in, and seeing if it matches?
(As I said, I don't know IntelliJ plugins, so that approach is probably impossible)

**Comment by DemonWav** [comment] 2016-09-12 11:53
To keep things simple I'm gonna file this one away as a duplicate of #28. It's not really, but once that issue is fully complete this one will also be complete by proxy.

**Closed by DemonWav** 2016-09-12 11:53 UTC
Labels: platform: forge, type: bug, type: duplicate
