### ISSUE TITLE
Incorrect Errors When Using MixinExtras

### ISSUE THREAD

**Issue by senseiwells** [DemonWav/MinecraftDevIntelliJ#2170] opened 2023-11-24 01:17 UTC
### Minecraft Development for IntelliJ plugin version

2023.2.2-1.6.11

### IntelliJ version

IntelliJ IDEA 2023.2.5 (Ultimate Edition) Build #IU-232.10227.8

### Operating System

MacOS 13.2.1

### Target platform

Fabric, Mixins

### Description of the bug

In the following example, IntelliJ gives the error that the parameters do not match the expected parameters, despite these being the correct parameters:
<img width="993" alt="SCR-20231124-bxay" src="https://github.com/minecraft-dev/MinecraftDev/assets/66843746/47758219-7714-4b6c-bac9-cd21d484f600">

If I apply the suggested fix:
<img width="540" alt="image" src="https://github.com/minecraft-dev/MinecraftDev/assets/66843746/e003e278-872f-47b9-be82-e641c499a90b">
And then run the server and join, the mixin will fail to apply:
```
Mixin apply for mod arcade failed arcade.mixins.json:minigame.FoodDataMixin from mod arcade -> net.minecraft.world.food.FoodData: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @WrapWithCondition condition wrapper method net/minecraft/world/food/FoodData::onDecreaseFood from arcade.mixins.json:minigame.FoodDataMixin from mod arcade has an invalid signature. Found unexpected argument type int at index 0, expected net.minecraft.world.food.FoodData. Handler signature: (II)Z Expected signature: (Lnet/minecraft/world/food/FoodData;I)Z [INJECT Applicator Phase -> arcade.mixins.json:minigame.FoodDataMixin from mod arcade -> Apply Injections ->  -> Inject -> arcade.mixins.json:minigame.FoodDataMixin from mod arcade->@WrapWithCondition::onDecreaseFood(II)Z]
```

**Comment by Earthcomputer** [comment] 2023-11-24 13:08
Duplicate of #1884

**Closed as completed by Earthcomputer** 2023-11-24 13:08 UTC
Labels: type: bug, status: unverified
