### ISSUE TITLE
Spigot and Bungee forces Gradle instead of Maven

### ISSUE THREAD

**Issue by rlnt** [DemonWav/MinecraftDevIntelliJ#693] opened 2020-03-19 16:28 UTC
- Plugin version: 2019.3-1.3.3
- IntelliJ version: 2019.3.4 Ultimate Edition
- OS: Windows 10 64-Bit 1909
- Target platforms: Spigot, Bungee

So I am used to develop either Spigot plugins or Bungee plugins but I now came to a point where I want to develop a plugin that needs to run on Spigot and Bungee.
Everytime I set up my projects with this amazing plugin (I really appreciate your work). Normally you are able to select if you want to use Maven or Gradle when setting up a new project like so:
![pic1](https://i.imgur.com/xiZ2nuD.png)

However, if you want to set up a plugin for Spigot and Bungee and check both options like this:
![pic2](https://i.imgur.com/LVGmfVQ.png)
you are no longer able to select if you want to use Maven or Gradle. When you set up the project , it uses Gradle automatically. I prefer Maven so why is there no option? Isn't that possible?

I know there is a workaround to just add the Bungee stuff manually to Maven when you set up a Spigot plugin but it would be a lot cooler if you could do that automatically with this plugin.

**Comment by DenWav** [comment] 2020-03-20 08:16
This is because multi-module support for Maven was never implemented, but in my new rewrite that I'm doing right now that functionality will be added.

Duplicate of #328

**Closed as completed by DenWav** 2020-03-20 08:16 UTC
Labels: type: duplicate, build: maven
