### ISSUE TITLE
Older version request

### ISSUE THREAD

**Issue by Codesnipez** [DemonWav/MinecraftDevIntelliJ#703] opened 2020-04-16 16:29 UTC
Hello, 
I just want to ask if its possible to get older versions for Minecraft because I want to create plugins for 1.8+ but the oldest version that it gives me is 1.12. So if it would be possible could you add more versions. Or if is possible to get older version of Minecraft Development how to get it because everytime I download it from IntelliJ IDEA website It doesn't show up or just has the same versions of Minecraft.

**Comment by Earthcomputer** [comment] 2020-04-16 16:29
Older versions stopped being supported deliberately

**Comment by DenWav** [comment] 2020-04-18 00:25
Duplicate of #76, #165, #190, #295, #296, #312

**Closed as completed by DenWav** 2020-04-18 00:25 UTC
Labels: type: duplicate, status: invalid
