### ISSUE TITLE
The project creation wizzard does not have group id but requires it

### ISSUE THREAD

**Issue by AnCarsenat** [DemonWav/MinecraftDevIntelliJ#2352] opened 2024-08-04 07:21 UTC
### Minecraft Development for IntelliJ plugin version

2024.1-1.8.0

### IntelliJ version

2024.1.4

### Operating System

windows 10

### Target platform

Fabric

### Description of the bug

![image](https://github.com/user-attachments/assets/692e5744-70bd-4559-b5d5-08c7d76e0c6d)
Asks for group id but it doesn't appear anywhere

**Comment by AnCarsenat** [comment] 2024-08-04 07:26
Nevermind, you need to set the window size to 70% in the settings

**Comment by AnCarsenat** [comment] 2024-08-04 07:28
Actually still and issue even at 70% I can't see anything 
![image](https://github.com/user-attachments/assets/d68a4aa4-7902-40c4-954b-bafb480741f3)
No scroll wheel aswell ...

**Comment by AnCarsenat** [comment] 2024-08-04 07:33
And the scroll wheel dissapears right after filling in any of the options

**Comment by RedNesto** [comment] 2024-08-04 08:21
Gotta love platform bugs, using the same versions I have a scrollbar but it seems to disappear sometimes for no reason. Toggling the Build System Properties group seems to restore it though.

Duplicate of https://github.com/minecraft-dev/MinecraftDev/issues/2336

**Closed as completed by RedNesto** 2024-08-04 08:21 UTC
Labels: type: bug, status: unverified

**Comment by AnCarsenat** [comment] 2024-08-07 18:09
I start from the bottom and move up slowly and avoid the list boxes
