### ISSUE TITLE
New Fabric project setup screen is not loading MC, Yarn, Loader and Loom versions

### ISSUE THREAD

**Issue by andriihorpenko** [DemonWav/MinecraftDevIntelliJ#1846] opened 2022-06-04 16:03 UTC
Creating a new Fabric project won't load any versions for MC, Yarn, Loader and Loom, hence I am unable to create a project.
<img width="888" alt="image" src="https://user-images.githubusercontent.com/13716167/172013970-4c6c60f2-266b-4c8e-b25a-ddb2763590c8.png">

Useful information:
* Minecraft Development for IntelliJ plugin version: 2022.1-1.5.19
* IntelliJ version: IntelliJ IDEA 2022.1.1 (Ultimate Edition)
* Operating System: macOS 12.4

**Comment by RedNesto** [comment] 2022-06-04 16:05
Duplicate of https://github.com/minecraft-dev/MinecraftDev/issues/1829

**Closed as completed by RedNesto** 2022-06-04 16:05 UTC
Labels: type: bug, type: duplicate
