### ISSUE TITLE
It freezes the IDEA when I'm writing the language file

### ISSUE THREAD

**Issue by SolidBlock-cn** [DemonWav/MinecraftDevIntelliJ#2035] opened 2023-05-13 04:01 UTC
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

2023.1.1

### Operating System

Windows 11

### Target platform

Fabric

### Description of the bug

When I'm writing my language file `en_us.json`, the IDEA freezes and cannot operate anything, until I use Task Manager to force to close it. It happens when the en_us language file has duplicate keys and I'm writing in one of the duplicate keys.
Here is my IDEA log:
[idea-logs-20230513-11540414334089283412156928.zip](https://github.com/minecraft-dev/MinecraftDev/files/11468810/idea-logs-20230513-11540414334089283412156928.zip)

**Comment by SolidBlock-cn** [comment] 2023-05-13 04:15
It happens when providing suggestions for keys in the `en_us` langauge file.

**Comment by SolidBlock-cn** [comment] 2023-05-13 04:32
![图片](https://github.com/minecraft-dev/MinecraftDev/assets/32444848/e3373eac-41e6-4b11-8a81-060a302c7f32)
I can reproduce the issue now. <del>First use `Ctrl+D` to duplicate a row in `en_us.json`, and then</del> write something in the key. Then the IDEA freezes. It seems to happen when providing suggestions. (Supplement: It seems to happen as long as I write something in the key in the `en_us.json`.)
I exported the logs again. The issue happens on 2023-05-13 12:28 (UTC+8).
[idea-logs-20230513-11540414334089283412156928.zip](https://github.com/minecraft-dev/MinecraftDev/files/11468857/idea-logs-20230513-11540414334089283412156928.zip)
[idea-logs-20230513-12412018395856058271861438.zip](https://github.com/minecraft-dev/MinecraftDev/files/11468870/idea-logs-20230513-12412018395856058271861438.zip)

**Comment by IlluSnow** [comment] 2023-05-13 10:36
I also found the issue just now. Is there any solutions?

**Comment by IlluSnow** [comment] 2023-05-13 10:38
Platform - Forge:1.16.5-36.2.34

**Comment by RedNesto** [comment] 2023-05-13 10:39
This has already been fixed in the nightly builds. Duplicate of #2030

**Closed as not planned by RedNesto** 2023-05-13 10:39 UTC
Labels: type: bug, status: unverified

**Comment by qouteall** [comment] 2023-05-21 12:00
Can you release a new version? This is kind of severe and already cause my code loss (IDE hangs before saving code). Not everyone uses the nightly build. Thanks.

**Comment by Gaming32** [comment] 2023-05-21 12:28
I'm on Stable and I have the fix
