### ISSUE TITLE
Quilt Loader Support

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#2131] opened 2023-09-23 19:34 UTC
### Minecraft Development for IntelliJ plugin version

1

### Description of the feature request

Please add Quilt Support as one of the fabrics owners is a transphob and doesnt allow some  trans developers to do stuff

**Comment by Earthcomputer** [comment] 2023-09-23 19:57
Duplicate of #1827

**Closed as completed by Earthcomputer** 2023-09-23 19:57 UTC
Labels: type: enhancement, status: unverified
