### ISSUE TITLE
Version selection missing when creating a fabric mod

### ISSUE THREAD

**Issue by BoaTheCrafter** [DemonWav/MinecraftDevIntelliJ#1850] opened 2022-06-08 16:04 UTC
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version
  * 2022.1-1.5.19
* IntelliJ version
  * 2022.1.2
* Operating System (this has come up enough times to be worth noting)
  * Arch Linux
* (optional) Target platform, if relevant
  * Fabric

When i try to create a new Fabric Mod Project, the areas and drop down menus for Minecraft, Yarn, Loader and Loom Versions are empty
![image](https://user-images.githubusercontent.com/53836554/172663527-95176d9d-42ae-4f02-be59-1a8195d82659.png)

 and i can create a new project, but get these two errors once the gradle build script runs

![image](https://user-images.githubusercontent.com/53836554/172663888-ad33f25e-430b-467a-9043-6c98a5dec371.png)

Which don't really make sense to me, since java 17 and java 18 should be supported.

**Comment by Technerder** [comment] 2022-06-08 16:08
Running into the same issue on both my Windows 10 and Debian 11 machines (running Java 17)

**Comment by RedNesto** [comment] 2022-06-08 16:53
Might be caused by this error: `java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.modrinth.com/v2/project/P7dR8mSH/version` (I had to fiddle with the coroutines to get it)

Might be caused by cloudflare maybe ?

**Comment by BoaTheCrafter** [comment] 2022-06-08 16:56
> Might be caused by cloudflare maybe ?

That would at least explain, why neither reinstalling the plugin, upgrading gradle, nor changing JDKs helped in any way

**Comment by CodexNotFound** [comment] 2022-06-08 17:49
This seems to be the same issue as #1829

**Comment by RedNesto** [comment] 2022-06-08 18:08
> This seems to be the same issue as https://github.com/minecraft-dev/MinecraftDev/issues/1829

It kinda is given they use the stable version and the mentionned bug is only fixed in the nightly versions but I also can't get fabric versions when using a nightly too, this time it seems to be a modrinth issue so we can't do anything but wait.

**Comment by Mysterious-Dev** [comment] 2022-06-08 18:10
Yep. Modrinth API is down. The only thing to do is to wait

**Comment by Mysterious-Dev** [comment] 2022-06-08 18:53
Modrinth API is back. It is now possible to obtain the following versions

**Comment by RedNesto** [comment] 2022-06-08 18:57
About the gradle issue with Java 18 you had, I just tried to generate a fabric project with Java 18 and it works fine, so I'll blame it on the first issue.

**Closed as completed by RedNesto** 2022-06-08 18:57 UTC
Labels: type: bug, status: unverified

**Comment by BoaTheCrafter** [comment] 2022-06-08 19:01
> About the gradle issue with Java 18 you had, I just tried to generate a fabric project with Java 18 and it works fine, so I'll blame it on the first issue.

Yeah, thought that too. Even thou it still wont show me the Versions, but i guess that will fix itself until tomorrow
