### ISSUE TITLE
Add function to select mapping between yarn and official mapping

### ISSUE THREAD

**Issue by SJKZ1-2565** [DemonWav/MinecraftDevIntelliJ#1929] opened 2023-01-15 03:48 UTC
### Minecraft Development for IntelliJ plugin version

2022.2-1.5.21

### Description of the feature request

Add function to select mapping between yarn and official mapping

**Comment by Earthcomputer** [comment] 2023-03-01 18:47
Duplicate of #771

**Closed as completed by Earthcomputer** 2023-03-01 18:47 UTC
Labels: type: enhancement, status: unverified
