### ISSUE TITLE
IntelliJ EAP (and normal ultimate) does not show any possibility to create a Minecraft Based project

### ISSUE THREAD

**Issue by CarinaSchoppe** [DemonWav/MinecraftDevIntelliJ#1823] opened 2022-04-07 10:34 UTC
IntelliJ EAP (and normal ultimate) does not show any possibility to create a Minecraft Based project

**Comment by CarinaSchoppe** [comment] 2022-04-07 10:35
Also the createEvent tab in "generate" is not visible or even existing

**Comment by Earthcomputer** [comment] 2022-04-07 12:26
Duplicate of #1822

**Closed as completed by Earthcomputer** 2022-04-07 12:26 UTC
Labels: type: bug, status: unverified
