### ISSUE TITLE
Project Wizard Outdated

### ISSUE THREAD

**Issue by Jaoow** [DemonWav/MinecraftDevIntelliJ#1978] opened 2023-03-24 22:12 UTC
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.2

### IntelliJ version

IU-231.8109.144

### Operating System

Windows

### Target platform

Spigot

### Additional description

My Project Wizard does not seem to be up-to-date

**Comment by Jaoow** [comment] 2023-03-24 22:12
![image](https://user-images.githubusercontent.com/57773902/227652944-e6c0f98c-41c4-410d-a0a0-185b65a764b9.png)

**Comment by Earthcomputer** [comment] 2023-03-24 22:13
Hello, can you please be more specific, what exactly is not up-to-date?

**Comment by Mysterious-Dev** [comment] 2023-03-31 13:18
Maybe plugin version ?

**Comment by KleverSE** [comment] 2023-04-03 21:44
I have this exact same issue

**Comment by anonymous123-code** [comment] 2023-04-04 08:38
Maybe duplicate of #1971 ?

**Closed as not planned** 2023-04-04 09:58 UTC
Labels: type: bug, status: unverified, feature: creator
