### ISSUE TITLE
No versions show

### ISSUE THREAD

**Issue by Anldernx** [DemonWav/MinecraftDevIntelliJ#1853] opened 2022-06-10 12:28 UTC
Hello,
if i want to create a new fabric project, i cant select any kind of version
Minecraft Development for IntelliJ plugin version: 2022.1-.1.5.19
IntelliJ version: 2022.1.2
Operating System: Windows 10 OS

**Comment by Mysterious-Dev** [comment] 2022-06-10 12:30
Fixed in the nightly builds

**Comment by RedNesto** [comment] 2022-06-10 12:30
Duplicate of https://github.com/minecraft-dev/MinecraftDev/issues/1829

**Closed as completed by RedNesto** 2022-06-10 12:30 UTC
Labels: type: bug, type: duplicate
