### ISSUE TITLE
Cannot click create when trying to make a project.

### ISSUE THREAD

**Issue by JordanFails** [DemonWav/MinecraftDevIntelliJ#2047] opened 2023-06-04 14:48 UTC
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

IU-231.9011.34

### Operating System

Mac OS X

### Target platform

Spigot

### Additional description

When i switched to Ultimate, I all of a sudden cannot create a new project when trying to start a Minecraft Plugin.

**Comment by Loot1** [comment] 2023-06-23 20:08
Same problem :/ Duplicate of #2039 

Some precisions : when I use the button "Create", the form input of the title of the project is highlighted. As if the content of the form input was not correct.

**Closed as completed** 2023-07-09 16:28 UTC
Labels: type: bug, status: unverified, feature: creator

**Comment by ColonelGerdauf** [comment] 2023-10-02 18:50
I can confirm that this still happens. No matter what setting I enter; no matter where the locations are; the "create" button is dead, with at most scanning index in the background. This issue is certainly not complete.

I should also note that it ALWAYS moves the focus to the title bar, as if that does anything about the problem.
