### ISSUE TITLE
Add Minestom (Server.jar Customs)

### ISSUE THREAD

**Issue by lucas11222** [DemonWav/MinecraftDevIntelliJ#1965] opened 2023-03-11 09:19 UTC
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.1

### Description of the feature request

**Minestom** 
Is a project open souce what create server.jar custom and add things that you can't just with plugin

**Comment by lucas11222** [comment] 2023-03-11 09:19
Page: https://minestom.net/
Wiki: https://wiki.minestom.net/
Video: https://www.youtube.com/watch?v=rV1y2RjH_xM&t

**Comment by RedNesto** [comment] 2023-09-24 08:56
Duplicate of #835

**Closed as completed by RedNesto** 2023-09-24 08:56 UTC
Labels: type: enhancement, status: unverified
